image: node:12

stages:
  - pre-build
  - build
  - post-build
  - test
  - deploy

cache:
  paths:
    - node_modules/

install-deps:
  stage: pre-build
  script:
    - npm install
  cache:
    paths:
      - node_modules/

build-app:
  stage: build
  before_script:
    - touch .env
    - echo "REACT_APP_API_URL=$REACT_APP_API_URL" > .env
    - echo "REACT_APP_SALT_ROUND=$REACT_APP_SALT_ROUND" >> .env
    - echo "REACT_APP_JWT_SECRET=$REACT_APP_JWT_SECRET" >> .env
    - echo "REACT_APP_AUTH_SECRET=$REACT_APP_AUTH_SECRET" >> .env
    - echo "REACT_APP_API_VERSION=$REACT_APP_API_VERSION" >> .env
  script:
    - npm run build
  artifacts:
    paths: 
      - build/

build-server:
  stage: post-build
  script:
    - npm run build:server
  artifacts:
    paths:
      - server/

tests:
  stage: test
  script: 
    - npm run test

deploy:
  stage: deploy
  before_script:
    - cd server
    - git init
    - git config user.email "vincent.crys.dev@gmail.com"
    - git config user.name "Flists"
  script:
    - ls
    - git add .
    - git commit -m "deployment"
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git
    - git push -f heroku HEAD:master
  environment:
    name: production
    url: https://flists-front.herokuapp.com/
  only:
    - master